### ISSUE TITLE
The days word is showing double in the packages card

### ISSUE THREAD

**Issue by sachinsherchan** [sachinsherchan/TourAndTravelWebApp#10]
![days](https://user-images.githubusercontent.com/82159329/116806986-519e6300-ab50-11eb-8040-5c1d8f516fcb.png)

Need to show only one word "days" instead showing double "days days", fix it through admin panel

**Comment by ggupshot** [comment]
![Screenshot (265)](https://user-images.githubusercontent.com/81247764/116817165-cee3cb00-ab84-11eb-844e-0efd1e7fc78d.png)


issue for days being doubled has been fixed
