### ISSUE TITLE
The page looks mismanaged due to unequal sizing of images.

### ISSUE THREAD

**Issue by AshimGhising** [sachinsherchan/TourAndTravelWebApp#11]
![issue5](https://user-images.githubusercontent.com/82171088/116808622-9084e680-ab59-11eb-9409-def2f069ddd6.png)
This page looks a little mismanaged due to difference in size of images, so please resize the image or replace it.

**Comment by ggupshot** [comment]
ok ashim i will be working on that.

**Comment by ggupshot** [comment]
![Screenshot (266)](https://user-images.githubusercontent.com/81247764/116817568-b07ecf00-ab86-11eb-90ce-874c0610daeb.png)



All Images has been resize to match each other
