### ISSUE TITLE
Footer link is not working.

### ISSUE THREAD

**Issue by HomBahadurChhetri** [sachinsherchan/TourAndTravelWebApp#12]
![issue 1](https://user-images.githubusercontent.com/81349733/117268411-f84b7200-ae76-11eb-9097-18e1d98d7a97.PNG)

**Comment by ggupshot** [comment]
![Screenshot (271)](https://user-images.githubusercontent.com/81247764/118095023-47e9ea80-b3ef-11eb-9e94-d39348a3761a.png)
the footer links are now working .
