### ISSUE TITLE
use a relevant company name

### ISSUE THREAD

**Issue by HomBahadurChhetri** [sachinsherchan/TourAndTravelWebApp#13]
![issue 2](https://user-images.githubusercontent.com/81349733/118074842-8cb15980-b3ce-11eb-8894-b85e8a180a6a.PNG)

**Comment by HomBahadurChhetri** [comment]
It could be something like Surya Tours and Travel.

**Comment by ggupshot** [comment]
how about we use something short and unique like [Travelo Nepal]

**Comment by sachinsherchan** [comment]
![issue name fixed](https://user-images.githubusercontent.com/82159329/118216630-994bb580-b493-11eb-82d5-679e7abcc746.png)


![issue name fixed 2](https://user-images.githubusercontent.com/82159329/118216649-a10b5a00-b493-11eb-9b36-f9d7cabbeb3b.png)

I have updated the name as Surya Tours and Travels
