### ISSUE TITLE
The package in review database isnot showing what user filled

### ISSUE THREAD

**Issue by HomBahadurChhetri** [sachinsherchan/TourAndTravelWebApp#14]
![issue3](https://user-images.githubusercontent.com/81349733/118075974-db5ff300-b3d0-11eb-9f62-72519aedf7e6.PNG)

**Comment by sachinsherchan** [comment]
![database showing package](https://user-images.githubusercontent.com/82159329/118363906-2f77fc80-b5b6-11eb-8752-9f00230b97df.png)

the package selected and submitted by the user is now showing to the database, the bug is fixed
