### ISSUE TITLE
posted date is not showing in blog_detail page

### ISSUE THREAD

**Issue by HomBahadurChhetri** [sachinsherchan/TourAndTravelWebApp#15]
![issue4](https://user-images.githubusercontent.com/81349733/118093987-e6754c00-b3ed-11eb-878f-af9656f3df22.PNG)

**Comment by ggupshot** [comment]
![Screenshot (270)](https://user-images.githubusercontent.com/81247764/118094546-98147d00-b3ee-11eb-8bb1-4dd42cf598bb.png)
the issue has been fixed
