### ISSUE TITLE
Terms and condition is missing in footer section

### ISSUE THREAD

**Issue by HomBahadurChhetri** [sachinsherchan/TourAndTravelWebApp#16]
![issue5](https://user-images.githubusercontent.com/81349733/118297768-507d1680-b4fe-11eb-99bf-8c7ce9109aa1.PNG)

**Comment by AshimGhising** [comment]
![solvedissue4](https://user-images.githubusercontent.com/82171088/118370670-8555a000-b5c8-11eb-9d48-6eaf410a9ceb.png)
Added Terms and Conditions link in footer section under Company Info that navigates to TermsandConditions page.
