### ISSUE TITLE
About us styling

### ISSUE THREAD

**Issue by sachinsherchan** [sachinsherchan/TourAndTravelWebApp#2]
the side section of Ask a Question seem to be taking more space

![enhance](https://user-images.githubusercontent.com/82159329/114302220-ce0ccb80-9ae7-11eb-84d4-d7b18c8cc549.png)

also the Company Info text can be aligned in Center

**Comment by AshimGhising** [comment]
Issue is solved. I have attached the screenshot of updated aboutus page below :
![updated](https://user-images.githubusercontent.com/82171088/114303242-e16e6580-9aec-11eb-8a72-6a3ac512503b.png)
Please have a look!
