### ISSUE TITLE
placeholder is same in both fields

### ISSUE THREAD

**Issue by ggupshot** [sachinsherchan/TourAndTravelWebApp#21]
![Screenshot 2021-05-14 220347](https://user-images.githubusercontent.com/81247764/118299440-79061000-b500-11eb-8e0b-498d253f2bbe.png)

**Comment by sachinsherchan** [comment]
![placehoder changed](https://user-images.githubusercontent.com/82159329/118362787-c2ae3380-b5b0-11eb-9ee7-2cdd7115b91c.png)

The bug for place holder showing same is fixed
