### ISSUE TITLE
Add a proper number and name on  homepage contact us section

### ISSUE THREAD

**Issue by pranav-regmi** [sachinsherchan/TourAndTravelWebApp#22]
On home page, contact us section, mention a proper number and a name of a person.
![Screenshot (131)](https://user-images.githubusercontent.com/81219577/118299442-7a373d00-b500-11eb-9b0f-995ceb7c6c07.png)

**Comment by AshimGhising** [comment]
![solvedissue5](https://user-images.githubusercontent.com/82171088/118371046-6952fe00-b5ca-11eb-9af4-359e874369a5.png)
Added proper contact details on contact section of the home page.
