### ISSUE TITLE
Add a number in footer section

### ISSUE THREAD

**Issue by pranav-regmi** [sachinsherchan/TourAndTravelWebApp#23]
On footer of every page, add a number on contact us.
![Screenshot (132)](https://user-images.githubusercontent.com/81219577/118299785-e87bff80-b500-11eb-923f-e155e817a42d.png)

**Comment by sachinsherchan** [comment]
![phoen](https://user-images.githubusercontent.com/82159329/118369395-e24e5780-b5c2-11eb-9d7b-d0decde16d20.png)

Phone number is added to the footer section
