### ISSUE TITLE
Add Text On footer on Social Media Section

### ISSUE THREAD

**Issue by pranav-regmi** [sachinsherchan/TourAndTravelWebApp#24]
On footer of every page, on social media add a text:"YouTube".
![Screenshot (133)](https://user-images.githubusercontent.com/81219577/118300282-7a840800-b501-11eb-9e89-df3361aa2a2c.png)

**Comment by sachinsherchan** [comment]
![youtube logo](https://user-images.githubusercontent.com/82159329/118368985-6227f200-b5c2-11eb-9590-a12224d47bf5.png)

YouTube is now showing and the issue is fixed
