### ISSUE TITLE
Tour package under Traveler in Testimonials section is not showing!

### ISSUE THREAD

**Issue by AshimGhising** [sachinsherchan/TourAndTravelWebApp#26]
![testimonialbug_issue](https://user-images.githubusercontent.com/82171088/118301183-83290e00-b502-11eb-9fd6-ebf8ccc1cc1d.png)
The tour package description is not showing under Traveler description in Testimonials section.

**Comment by sachinsherchan** [comment]
![package showing in testomonials](https://user-images.githubusercontent.com/82159329/118363439-166e4c00-b5b4-11eb-9b72-6f8c4120cc6f.png)

The package which the user has selected is showing in the testimonial section, the bug is fixed.
