### ISSUE TITLE
Replace the image with dummy placeholder

### ISSUE THREAD

**Issue by sachinsherchan** [sachinsherchan/TourAndTravelWebApp#27]
![placehoder](https://user-images.githubusercontent.com/82159329/118303423-27ac4f80-b505-11eb-9ddb-32aba8c8e540.png)

Please update the image with a dummy image

**Comment by ggupshot** [comment]
![Screenshot (276)](https://user-images.githubusercontent.com/81247764/118303674-70640880-b505-11eb-898d-36815f85400f.png)
images have been updated with person placeholder images
