### ISSUE TITLE
Place the content on the middle by css

### ISSUE THREAD

**Issue by sachinsherchan** [sachinsherchan/TourAndTravelWebApp#28]
![place in middel](https://user-images.githubusercontent.com/82159329/118303705-7954da00-b505-11eb-8931-b95a62cb7926.png)

The content here seems to be stuck at the left side, keeping it on the center would look good

**Comment by ggupshot** [comment]
![Screenshot (295)](https://user-images.githubusercontent.com/81247764/118364608-d3fb3e00-b5b8-11eb-9a4d-0c9a20000c65.png)

**Comment by ggupshot** [comment]
the enhancement has been done to this page
