### ISSUE TITLE
Read more button in blog page is just showing underline

### ISSUE THREAD

**Issue by sachinsherchan** [sachinsherchan/TourAndTravelWebApp#29]
![read more buttion](https://user-images.githubusercontent.com/82159329/118303979-cc2e9180-b505-11eb-9de6-101eaa6c7906.png)

Making the a tag for read more can be shown as a button

**Comment by ggupshot** [comment]
![Screenshot 2021-05-15 192112](https://user-images.githubusercontent.com/81247764/118363159-c347c980-b5b2-11eb-8fa4-5edcf714f610.png)
the issue has been fixed

**Comment by ggupshot** [comment]
![Screenshot 2021-05-15 192112](https://user-images.githubusercontent.com/81247764/118363182-e6727900-b5b2-11eb-8336-ca4d0974e79f.png)

**Comment by ggupshot** [comment]
![Uploading Screenshot 2021-05-15 192210.png…]()

**Comment by ggupshot** [comment]
![Uploading Screenshot 2021-05-15 192210.png…]()

**Comment by ggupshot** [comment]
![Uploading Screenshot 2021-05-15 192210.png…]()
