### ISSUE TITLE
The linking to pages from about us page in not working

### ISSUE THREAD

**Issue by sachinsherchan** [sachinsherchan/TourAndTravelWebApp#30]
![about us nav not working](https://user-images.githubusercontent.com/82159329/118313517-8c21db80-b512-11eb-8805-6b4876f9a888.png)

**Comment by AshimGhising** [comment]
![solvedissue3](https://user-images.githubusercontent.com/82171088/118363035-356bde80-b5b2-11eb-91bb-f04f0d92905b.png)
This issue has been solved. The navigation links present on about us page now work and the link navigates to the respective pages.
