### ISSUE TITLE
Dropdown menu is not showing on review form!

### ISSUE THREAD

**Issue by AshimGhising** [sachinsherchan/TourAndTravelWebApp#32]
![review_issue](https://user-images.githubusercontent.com/82171088/118359745-a86e5880-b5a4-11eb-8f66-4febcf810ed6.png)
The list of packages from the database must be displayed.

**Comment by sachinsherchan** [comment]
![database review](https://user-images.githubusercontent.com/82159329/118361239-3731a400-b5aa-11eb-9048-37265f055627.png)

The dropdown option for which package did you choose is now working
