### ISSUE TITLE
Increase the char length in models.py for the model guide as the full text is not being displayed

### ISSUE THREAD

**Issue by sachinsherchan** [sachinsherchan/TourAndTravelWebApp#33]
![full not showing](https://user-images.githubusercontent.com/82159329/118368418-c6968180-b5c1-11eb-91be-5f824e263b15.png)

**Comment by ggupshot** [comment]
![Uploading Screenshot (297).png…]()

**Comment by ggupshot** [comment]
the issue has now been solved. also the database is updated
