### ISSUE TITLE
The aboutus link in homepage navbar is not working.

### ISSUE THREAD

**Issue by AshimGhising** [sachinsherchan/TourAndTravelWebApp#4]
![aboutuse](https://user-images.githubusercontent.com/82171088/114427885-443e2a80-9bdb-11eb-972a-ea62489c8f24.png)

**Comment by sachinsherchan** [comment]
The home page navbar bug is now solved

![fixed ](https://user-images.githubusercontent.com/82159329/114485551-d9690f80-9c2b-11eb-80b6-9814139e1ec6.png)
