### ISSUE TITLE
generate relevant information on About Us section In home page

### ISSUE THREAD

**Issue by HomBahadurChhetri** [sachinsherchan/TourAndTravelWebApp#5]
I found that dummy text is generated on about us section in home page. so, please give the correct information in about us section as it leaves good impression on user.

**Comment by sachinsherchan** [comment]
Updated the dummy text for the about us section of the home page


![about](https://user-images.githubusercontent.com/82159329/114722333-6f4e8880-9d59-11eb-8c71-41f0c18a542d.png)

**Comment by ggupshot** [comment]
ok i will work on it
