### ISSUE TITLE
Copyright Logo

### ISSUE THREAD

**Issue by HomBahadurChhetri** [sachinsherchan/TourAndTravelWebApp#6]
copyright logo seems to be in the left-side of the webpage.  so, I think it will look better if it is in the middle of the page.

**Comment by HomBahadurChhetri** [comment]
We are very near to the end of first sprint. So, work harder and solve the Issue.

**Comment by sachinsherchan** [comment]
Kept the copyright Logo on the center 

![issue 2](https://user-images.githubusercontent.com/82159329/114552876-c2a2d700-9c84-11eb-91c6-7e697ec61b6e.png)
