### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by HomBahadurChhetri** [sachinsherchan/TourAndTravelWebApp#7]
the button in navigation bar are large. so, make it a bit smaller.

**Comment by ggupshot** [comment]
ok  i will check on that

**Comment by ggupshot** [comment]
![Screenshot (166)_LI](https://user-images.githubusercontent.com/81247764/114992413-7345ec00-9eba-11eb-8bdc-b594d0ee82c9.jpg)
