### ISSUE TITLE
The slug on the Tilman package post is not showing

### ISSUE THREAD

**Issue by sachinsherchan** [sachinsherchan/TourAndTravelWebApp#9]
![tilmaa](https://user-images.githubusercontent.com/82159329/116806720-9d500d00-ab4e-11eb-8b13-eef8eff49fab.png)

need to show tilman-package on the url, currently showing package only

**Comment by ggupshot** [comment]
ok i will work on that asap

**Comment by ggupshot** [comment]
![Screenshot (264)](https://user-images.githubusercontent.com/81247764/116817071-701e5180-ab84-11eb-954a-0431caadfdce.png)

**Comment by ggupshot** [comment]
Bug has been fixed for tilmanpass slug routing
